stages:
  - deploy

deploy:
  stage: deploy
  only:
    refs:
      - tags
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "https://git.ipoteka.digital/api/v4/projects/$CI_PROJECT_ID/packages/composer"'